### ISSUE TITLE
[ Deleted ]

### ISSUE THREAD

**Issue by abhishekbalam** [FOSSTribe/meta#5]
[ Deleted ]

**Comment by hemanth** [comment]
Thanks for the issue, it would be useful if you could summarize the idea here.

**Comment by SudHegde** [comment]
Good idea on technology front 👍  Totally agree on providing insights for medical companies and govt. There can be few issues in practice though-
- As the medical data is highly confidential, hard to trust anyone with access to medical records of billions of people.
- Millions of Indians are still technology illiterates, so it can not be made mandatory, and as long as there are still paper prescriptions, there is still ample opportunity for fraud.

**Comment by abhishekbalam** [comment]
Thank you for your input @SudHegde, I really appreciate it. Please let me address your concerns below, in order:

- Thats why the code and the systems to develop analytics/insights should be open to the public. Only the data should be walled off and controlled by one person who is accountable. Thats why I dont mind putting out this idea in the open. Im looking to create an open standard for E-Prescription accepted after thorough scrutiny by experts from the govt and outside.
- Yap, bt the adoption of technology is inevitable. E-Voting for example was implemented in 1999, that shows that if the technology convinces the govt of its merits, it will be implemented. With data costs reducing and many people coming online every day, it's only a matter of time. Besides, the patient may not need to understand any part of the tech also, just the doctors and the pharmacists. Even in the present system, we dont really understand the content of the prescriptions. As for pharmacists, they are already required to keep electronic records of sales (which they pay to do right now).
